name: Lint Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install @commitlint/{config-conventional,cli}
      - run: npx commitlint --from=origin/main --to=HEAD
